name: CI/CD Pipeline - React/Vite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  ci:
    name: Validar & Compilar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar Linter
        run: npm run lint

      - name: Executar Testes
        run: npm test

      - name: Executar Build
        run: npm run build